<?php

declare(strict_types=1);

/*
|--------------------------------------------------------------------------
| Report language — shipped defaults
|--------------------------------------------------------------------------
|
| Every fixed word or phrase that appears on a client-facing report lives
| here: section headings, metric labels, table headers, chart titles, legend
| text, empty-state sentences and the auto-written summary sentences.
|
| DO NOT edit this file to customise wording — it is tracked in git and an
| update will overwrite it. Instead copy `config/report-language.local.php.example`
| to `config/report-language.local.php` (git-ignored) and set only the keys you
| want to change. That override is deep-merged over these defaults, so anything
| you leave out — including keys added by future updates — keeps working in the
| shipped language. See App\Support\ReportLang.
|
| Dynamic values are injected where you see a `:name` placeholder; keep the
| placeholder in your wording or the value will not appear.
|
*/

return [

    /*
    | Shared strings — chrome that appears across many blocks.
    */
    'common' => [
        'source' => 'Source',
        'summary_label' => 'Summary',
        'ai_summary_label' => 'AI summary',
        'no_change' => 'No change',
        'vs_prev' => ':delta% vs prev.',
        'no_data' => 'No data',
        'direct' => 'Direct',
        'unknown' => 'Unknown',
        'this_period' => 'This period',
        'previous_period' => 'Previous period',
        'php_version' => 'PHP version',
        'incident_reason_down' => 'Down',
        'monitor_fallback' => 'Monitor',
        'direction' => [
            'up' => 'up',
            'down' => 'down',
        ],
        'incidents_col' => [
            'service' => 'Service',
            'started' => 'Started',
            'duration' => 'Duration',
            'reason' => 'Reason',
        ],
        'empty' => [
            'analytics' => 'No analytics data was collected for this period yet.',
            'uptime' => 'No uptime data was collected for this period yet.',
            'events' => 'No custom events recorded for this analytics property in this period.',
        ],
    ],

    /*
    | Auto-written "at a glance" sentence shared by several blocks
    | (App\Reporting\Support\Insight).
    */
    'insight' => [
        'this_period' => ':value :noun this period.',
        'unchanged' => ':value :noun, unchanged from the prior period.',
        'changed' => ':value :noun, :direction :percent% from the prior period.',
    ],

    /*
    | Cover.
    */
    'cover' => [
        'eyebrow' => 'Website report',
        'prepared_for' => 'Prepared for',
        'label' => 'Cover',
    ],

    /*
    | Contents.
    */
    'contents' => [
        'heading' => 'Contents',
        'empty' => 'Add other sections to this report to see them listed here.',
    ],

    /*
    | Website overview.
    */
    'website_overview' => [
        'heading' => 'Website overview',
        'row' => [
            'website' => 'Website',
            'platform' => 'Platform',
            'environment' => 'Environment',
        ],
    ],

    /*
    | Closing message.
    */
    'closing' => [
        'heading' => 'Thank you',
        'get_in_touch' => 'Get in touch:',
        'label' => 'Closing message',
    ],

    /*
    | Free-text / commentary block.
    */
    'text' => [
        'empty' => 'Add your commentary for this section.',
        'label' => 'Text & commentary',
    ],

    /*
    | A block that could not be rendered.
    */
    'unavailable' => [
        'body' => 'This section is temporarily unavailable.',
    ],

    /*
    | Site traffic (the consolidated analytics block).
    */
    'traffic' => [
        'heading' => 'Site traffic',
        'bounce_rate_label' => 'Avg bounce rate :rate',
        'visitors_over_time' => 'Visitors over time',
        'mini' => [
            'top_pages' => 'Top pages',
            'unit_pageviews' => 'pv',
            'top_referrers' => 'Top referrers',
            'top_countries' => 'Top countries',
            'top_devices' => 'Top devices',
        ],
        'tile' => [
            'visitors' => 'Visitors',
            'visits' => 'Visits',
            'pageviews' => 'Pageviews',
            'avg_duration' => 'Avg. duration',
        ],
        // Auto-written summary, assembled clause by clause.
        'summary' => [
            'visitor' => 'visitor',
            'visitors' => 'visitors',
            'base' => ':count :noun this period',
            'growth' => ', :direction :percent% on the previous period',
            'source' => ':source was the largest source',
            'device' => ', with :device the most common device',
        ],
    ],

    /*
    | Analytics summary (the itemised metric block).
    */
    'analytics' => [
        'heading' => 'Analytics',
        'label' => 'Analytics summary',
        'insight_noun' => 'visitors',
        'metric' => [
            'visitors' => 'Visitors',
            'pageviews' => 'Page views',
            'visits' => 'Visits',
            'bounce_rate' => 'Bounce rate',
            'visit_duration' => 'Avg visit duration',
        ],
    ],

    /*
    | Visitors-per-day chart block.
    */
    'analytics_chart' => [
        'heading' => 'Visitors per day',
        'label' => 'Visitors chart',
        'empty' => 'No daily data for this period.',
    ],

    /*
    | Traffic sources block.
    */
    'sources' => [
        'heading' => 'Where visitors came from',
        'label' => 'Traffic sources',
        'empty' => 'No source data for this period.',
    ],

    /*
    | Top devices block.
    */
    'devices' => [
        'heading' => 'Top devices',
        'empty' => 'No device data for this period.',
    ],

    /*
    | Top countries block.
    */
    'countries' => [
        'heading' => 'Top countries',
        'empty' => 'No country data for this period.',
    ],

    /*
    | Top pages block.
    */
    'top_pages' => [
        'heading' => 'Top pages',
        'empty' => 'No page data for this period.',
        'col' => [
            'page' => 'Page',
            'views' => 'Views',
            'visitors' => 'Visitors',
        ],
    ],

    /*
    | Custom events block.
    */
    'events' => [
        'heading' => 'Custom events',
        'item_fallback' => 'Event',
    ],

    /*
    | Uptime & performance (consolidated) and its parts.
    */
    'uptime_overview' => [
        'heading' => 'Uptime & performance',
        'daily_uptime' => 'Daily uptime',
        'lighthouse_scores' => 'Lighthouse scores',
        'performance_over_time' => 'Performance score over time',
        'incidents_heading' => 'Incidents this period',
        'no_outages' => 'No outages detected during this period. 🎉',
    ],
    'uptime' => [
        'legend' => [
            'healthy' => 'Healthy',
            'partial' => 'Partial',
            'below' => 'Below 99.5%',
            'none' => 'No check',
        ],
        'tile' => [
            'uptime' => 'Uptime',
            'response' => 'Response',
            'incidents' => 'Incidents',
            'downtime' => 'Downtime',
            'cert_alerts' => 'Cert alerts',
            'monitors' => 'Monitors',
        ],
        'metric' => [
            'uptime' => 'Uptime',
            'incidents' => 'Incidents',
            'downtime' => 'Downtime',
            'avg_response' => 'Avg response',
        ],
        // Auto-written summary, assembled clause by clause.
        'summary' => [
            'base' => 'The site held :uptime uptime',
            'response' => ' with an average response time of :response.',
            'no_response' => ' this period.',
            'incident_singular' => ' :count incident was detected during the period.',
            'incident_plural' => ' :count incidents were detected during the period.',
            'lighthouse' => ' Lighthouse performance sits at :score.',
        ],
    ],
    'lighthouse' => [
        'performance' => 'Performance',
        'accessibility' => 'Accessibility',
        'best_practices' => 'Best practices',
        'seo' => 'SEO',
    ],

    /*
    | Uptime incidents block.
    */
    'incidents' => [
        'heading' => 'Incidents',
        'no_outages' => 'No outages were recorded during this period. 🎉',
    ],

    /*
    | Uptime summary block.
    */
    'uptime_summary' => [
        'heading' => 'Uptime & availability',
        'label' => 'Uptime summary',
    ],

    /*
    | SSL certificates block.
    */
    'certificates' => [
        'heading' => 'SSL certificates',
        'empty' => 'No certificate data was collected for this period yet.',
        'col' => [
            'endpoint' => 'Endpoint',
            'expires_in' => 'Expires in',
            'status' => 'Status',
        ],
        'expiry' => [
            'expired' => 'Expired',
            'one_day' => '1 day',
            'days' => ':days days',
        ],
        'status' => [
            'valid' => 'Valid',
            'renew_soon' => 'Renew soon',
            'expired' => 'Expired',
            'renew_now' => 'Renew now',
        ],
    ],

    /*
    | Performance / Core Web Vitals block.
    */
    'performance' => [
        'heading' => 'Core Web Vitals',
        'empty' => 'No performance data was collected for this period yet.',
        'score_label' => 'Performance',
        'score_suffix' => '/100',
        'rating' => [
            'good' => 'Good',
            'needs_work' => 'Needs work',
            'poor' => 'Poor',
        ],
        'source' => [
            'field' => 'real-user data',
            'lab' => 'lab test',
        ],
        'vital' => [
            'lcp' => ['key' => 'LCP', 'label' => 'Largest Contentful Paint'],
            'inp' => ['key' => 'INP', 'label' => 'Interaction to Next Paint'],
            'cls' => ['key' => 'CLS', 'label' => 'Cumulative Layout Shift'],
        ],
        // Auto-written insight, assembled clause by clause.
        'insight' => [
            'rating_good' => 'a good',
            'rating_needs' => 'a needs-improvement',
            'rating_poor' => 'a poor',
            'base' => 'The site scored :score on performance, :rating rating.',
            'attention_singular' => ' :vitals needs attention.',
            'attention_plural' => ' :vitals need attention.',
        ],
    ],

    /*
    | Search performance block.
    */
    'search' => [
        'heading' => 'Search performance',
        'source' => 'Google Search Console',
        'empty' => 'No search data was collected for this period yet.',
        'clicks_over_time' => 'Search clicks over time',
        'insight_noun' => 'clicks from Google search',
        'metric' => [
            'clicks' => 'Clicks',
            'impressions' => 'Impressions',
            'ctr' => 'CTR',
            'avg_position' => 'Avg position',
        ],
        'queries' => [
            'col' => [
                'queries' => 'Top queries',
                'clicks' => 'Clicks',
                'impressions' => 'Impressions',
                'ctr' => 'CTR',
                'position' => 'Position',
            ],
        ],
        'pages' => [
            'col' => [
                'pages' => 'Top landing pages',
                'clicks' => 'Clicks',
                'impressions' => 'Impressions',
                'ctr' => 'CTR',
                'position' => 'Position',
            ],
        ],
    ],

    /*
    | Downloads block.
    */
    'downloads' => [
        'heading' => 'Downloads',
        'empty' => 'No download data was collected for this period yet.',
        'over_time' => 'Downloads over time',
        'col' => [
            'top_files' => 'Top files',
            'downloads' => 'Downloads',
        ],
    ],

    /*
    | Ecommerce / store performance block.
    */
    'ecommerce' => [
        'heading' => 'Store performance',
        'empty' => 'No store was detected on this site for the period.',
        'product_fallback' => 'Product',
        'col' => [
            'top_products' => 'Top products',
            'revenue' => 'Revenue',
            'sold' => 'Sold',
        ],
        'metric' => [
            'revenue' => 'Revenue',
            'orders' => 'Orders',
            'aov' => 'Avg order',
            'items_sold' => 'Items sold',
        ],
        // Auto-written insight, assembled clause by clause.
        'insight' => [
            'order' => 'order',
            'orders' => 'orders',
            'base' => 'The store processed :count :noun totalling :revenue in net revenue',
            'no_compare' => ' this period.',
            'unchanged' => ', unchanged from the prior period.',
            'changed' => ', :direction :percent% from the prior period.',
        ],
    ],

    /*
    | Ads / ad performance block.
    */
    'ads' => [
        'heading' => 'Ad performance',
        'empty' => 'No ad platform data was collected for this period yet.',
        'metric' => [
            'spend' => 'Spend',
            'clicks' => 'Clicks',
            'impressions' => 'Impressions',
            'conversions' => 'Conversions',
        ],
        'insight' => [
            'click' => 'click',
            'clicks' => 'clicks',
            'text' => 'Ads spent :spend for :count :noun this period.',
        ],
    ],

    /*
    | Forms / leads & signups block.
    */
    'leads' => [
        'heading' => 'Leads & signups',
        'empty' => 'No leads data was collected for this period yet.',
        'metric' => [
            'new_leads' => 'New leads',
            'total_audience' => 'Total audience',
        ],
        'insight' => [
            'singular' => ':count new lead was captured this period.',
            'plural' => ':count new leads were captured this period.',
        ],
    ],

    /*
    | Billing & invoices block.
    */
    'billing' => [
        'heading' => 'Billing & invoices',
        'empty' => 'No invoices were raised for this period.',
        'insight_noun' => 'invoiced',
        'col' => [
            'invoice' => 'Invoice',
            'status' => 'Status',
            'issued' => 'Issued',
            'amount' => 'Amount',
        ],
        'metric' => [
            'invoiced' => 'Invoiced',
            'paid' => 'Paid',
            'outstanding' => 'Outstanding',
            'overdue' => 'Overdue',
        ],
        'status' => [
            'overdue' => 'Overdue',
        ],
        'insight' => [
            'no_compare' => ':total invoiced this period.',
            'overdue_singular' => ' :count invoice is overdue.',
            'overdue_plural' => ' :count invoices are overdue.',
        ],
    ],

    /*
    | CMS status block (e.g. WordPress).
    */
    'cms_status' => [
        'heading' => 'CMS status',
        'empty' => 'No CMS data has been collected yet.',
        'row' => [
            'wordpress_version' => 'WordPress version',
            'active_theme' => 'Active theme',
            'site_health' => 'Site Health',
            'users' => 'Users',
        ],
    ],

    /*
    | CMS updates block.
    */
    'cms_updates' => [
        'heading' => 'Updates',
        'applied_heading' => 'Applied this period',
        'pending_heading' => 'Currently pending',
        'care_note' => 'These updates are reported for your awareness. We apply them as part of your care plan.',
        'plugin_fallback' => 'Plugin',
        'insight' => [
            'applied_singular' => 'We applied :count update this period to keep the site current and secure.',
            'applied_plural' => 'We applied :count updates this period to keep the site current and secure.',
            'none' => 'No updates were needed this period — the site is fully up to date.',
            'pending_singular' => 'No updates were applied this period. :count update is currently pending.',
            'pending_plural' => 'No updates were applied this period. :count updates are currently pending.',
        ],
        'pill' => [
            'core' => 'Core update available',
            'plugins_singular' => ':count plugin update',
            'plugins_plural' => ':count plugin updates',
            'themes_singular' => ':count theme update',
            'themes_plural' => ':count theme updates',
        ],
        'applied' => [
            'col' => [
                'item' => 'Item',
                'type' => 'Type',
                'version' => 'Version',
                'date' => 'Date',
            ],
        ],
        'plugins' => [
            'col' => [
                'plugin' => 'Plugin',
                'installed' => 'Installed',
                'available' => 'Available',
            ],
        ],
    ],

    /*
    | Craft CMS status block.
    */
    'craft_status' => [
        'heading' => 'Craft status',
        'empty' => 'No Craft data has been collected yet.',
        'row' => [
            'craft_version' => 'Craft version',
            'environment' => 'Environment',
            'queue' => 'Queue',
            'licence' => 'Licence',
        ],
        'queue' => [
            'failed' => ':count failed',
            'pending' => ':count pending',
            'healthy' => 'Healthy',
        ],
    ],

    /*
    | AI summary / month in review block.
    */
    'ai_summary' => [
        'heading' => 'Month in review',
    ],

    /*
    | Public share-link gateway pages (seen by clients following a report link).
    */
    'public' => [
        'password' => [
            'title' => 'Protected report',
            'heading' => 'This report is protected',
            'body' => 'Enter the password you were given to view it.',
            'placeholder' => 'Password',
            'button' => 'View report',
            'error' => 'That password was not correct.',
        ],
        'unavailable' => [
            'title' => 'Report unavailable',
            'heading' => 'This report link is no longer available',
            'body' => 'The link may have expired or been revoked. Please contact the sender for an up-to-date link.',
        ],
    ],

];
